import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "User Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div style={{ display: "flex" }}>
          <Sidebar />
          <div style={{ marginLeft: "200px", width: "calc(100vw - 200px)" }}>
            <Header />
            <main
              style={{
                padding: "20px",
              }}
            >
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
